// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhQrfq8NShfOjJSmH4Cbhlev6Lvj4ZnXw',
    appId: '1:926357815822:web:10121090371fd107ae325f',
    messagingSenderId: '926357815822',
    projectId: 'kas-organisasi-app-e5fe2',
    authDomain: 'kas-organisasi-app-e5fe2.firebaseapp.com',
    storageBucket: 'kas-organisasi-app-e5fe2.firebasestorage.app',
    measurementId: 'G-WQL5JY485B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAksQnq8w-nQyvSvtL-FUS5JDJseLcG4R0',
    appId: '1:926357815822:android:b737dd900bcb3cbcae325f',
    messagingSenderId: '926357815822',
    projectId: 'kas-organisasi-app-e5fe2',
    storageBucket: 'kas-organisasi-app-e5fe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHZjFqgY143m3b2vOjNZDYZQyISooj-sg',
    appId: '1:926357815822:ios:92259792e89c0b78ae325f',
    messagingSenderId: '926357815822',
    projectId: 'kas-organisasi-app-e5fe2',
    storageBucket: 'kas-organisasi-app-e5fe2.firebasestorage.app',
    iosBundleId: 'com.example.kokas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHZjFqgY143m3b2vOjNZDYZQyISooj-sg',
    appId: '1:926357815822:ios:92259792e89c0b78ae325f',
    messagingSenderId: '926357815822',
    projectId: 'kas-organisasi-app-e5fe2',
    storageBucket: 'kas-organisasi-app-e5fe2.firebasestorage.app',
    iosBundleId: 'com.example.kokas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhQrfq8NShfOjJSmH4Cbhlev6Lvj4ZnXw',
    appId: '1:926357815822:web:d96818afef04c956ae325f',
    messagingSenderId: '926357815822',
    projectId: 'kas-organisasi-app-e5fe2',
    authDomain: 'kas-organisasi-app-e5fe2.firebaseapp.com',
    storageBucket: 'kas-organisasi-app-e5fe2.firebasestorage.app',
    measurementId: 'G-D20YX95BEN',
  );
}
